name: lambda-build-and-deploy

on:
  push:
    branches:
      - main

# Download and set up a version of Python that does not come preinstalled on an image
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: flake8 lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,E122,F841"
          max-line-length: "100"
# zip our code for lambda deployment
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./code.zip ./
# our application deploy to AWS lambda. I added my aws secret id and secret access key to my repository secret section
      - name: lambda  deployment
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: csv-s3-trigger
          zip_file: code.zip
